stages:
  - build
  - test
  - run

variables:
  GO_VERSION: "1.25"

# Build job
build_job:
  stage: build
  image: golang:${GO_VERSION}-alpine
  script:
    - echo "Initializing Go module..."
    - go mod init go_template_v3 || echo "Module already initialized"
    - echo "Downloading dependencies..."
    - go mod tidy
    - echo "Building the app..."
    - go build -o go_template_v3 ./cmd/go_template_v3
  artifacts:
    paths:
      - go_template_v3

# Test job
test_job:
  stage: test
  image: golang:${GO_VERSION}-alpine
  script:
    - echo "Running tests..."
    - go test ./...

# Run job
run_job:
  stage: run
  image: golang:${GO_VERSION}-alpine
  dependencies:
    - build_job
  script:
    - echo "Running the app..."
    - ./go_template_v3