sonar.projectKey=development7734933_go_template_v3.1_251ddc65-4c9a-485c-bd30-fc44c539c971
sonar.qualitygate.wait=true

# must be unique in SonarQube
sonar.projectKey=development7734933_go_template_v3.1_251ddc65-4c9a-485c-bd30-fc44c539c971
sonar.projectName=go_template_v3.1
sonar.projectVersion=1.0

# path to source code
sonar.sources=.

# language (optional, auto-detected)
sonar.language=java

# server URL
sonar.host.url=http://localhost:9000

# login token (generated in SonarQube: My Account → Security → Tokens)
sonar.login=sqp_573bbca9a478c51620618e8e83c663c2e7dc01ed